pathadd() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        PATH="${PATH:+$PATH:}$1"
    fi
}

# pathadd "$HOME/bin"
# pathadd "$HOME/.local/bin"
pathadd "$HOME/.cargo/bin"
# pathadd "$HOME/.npm-global/bin"
# pathadd "$HOME/go/bin"

unset -f pathadd

export EDITOR=nvim
export VISUAL=nvim
export LESS='-iRF'
export SYSTEMD_EDITOR=nvim
export SYSTEMD_PAGER=less
export BAT_THEME='ansi'

