# CentOS
export SEND_256_COLORS_TO_REMOTE=1

export PATH=/usr/bin:/usr/sbin:/opt/ibutils/bin:/usr/local/sbin:/usr/local/bin:/workspace/bin
PATH="$HOME/.cargo/bin:$PATH"
PATH="$HOME/go/bin:$PATH"
PATH="$HOME/bin:$PATH"

export EDITOR=nvim
export VISUAL=nvim
export SYSTEMD_EDITOR=nvim
export SYSTEMD_PAGER=less
export LESS='-iRF'
export BAT_THEME='ansi-dark'

